<script lang="ts">
	import { t } from "svelte-i18n";
</script>

<svelte:head>
	<title>Privacy Policy - {$t("page_titles.suffix")}</title>
</svelte:head>

<div class="page">
	<h1>{$t("pages.privacy.title")}</h1>
	<p>{$t("pages.privacy.last_updated")}</p>
	<p>
		{$t("pages.prvacy.policy_description")}
	</p>
	<p>
		{$t("pages.privacy.personal_data")}
	</p>
	<h1>{$t("pages.privacy.interpretation_definitions.title")}</h1>
	<h2>{$t("pages.privacy.interpretation_definitions.interpretation.header")}</h2>
	<p>
		{$t("pages.privacy.interpretation_definitions.interpretation.description")}
	</p>
	<h2>{$t("pages.privacy.interpretation_definitions.definitions.header")}</h2>
	<p>{$t("pages.privacy.interpretation_definitions.definitions.purposes")}</p>
	<ul>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_account")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_affiliate_description")}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_affiliate")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_affiliate_description")}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_application")}</strong
				>
				{$t(
					"pages.privacy.interpretation_definitions.definitions.purposes_application_description",
				)}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_company")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_company_description")}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_country")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_country_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.interpretation_definitions.definitions.purposes_device")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_device_description")}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t(
						"pages.privacy.interpretation_definitions.definitions.purposes_do_not_track",
					)}</strong
				>
				{$t(
					"pages.privacy.interpretation_definitions.definitions.purposes_do_not_track_description",
				)}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t(
						"pages.privacy.interpretation_definitions.definitions.purposes_personal_data",
					)}</strong
				>
				{$t(
					"pages.privacy.interpretation_definitions.definitions.purposes_personal_data_description",
				)}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_service")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_service_description")}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t(
						"pages.privacy.interpretation_definitions.definitions.purposes_service_provider",
					)}</strong
				>
				{$t(
					"pages.privacy.interpretation_definitions.definitions.purposes_service_provider_description",
				)}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t(
						"pages.privacy.interpretation_definitions.definitions.purposes_third_party_social_media_service",
					)}</strong
				>
				{$t(
					"pages.privacy.interpretation_definitions.definitions.purposes_third_party_social_media_service_description",
				)}
			</p>
		</li>
		<li>
			<p>
				<strong
					>{$t("pages.privacy.interpretation_definitions.definitions.purposes_usage_data")}</strong
				>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_usage_data_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.interpretation_definitions.definitions.purposes_you")}</strong>
				{$t("pages.privacy.interpretation_definitions.definitions.purposes_you_description")}
			</p>
		</li>
	</ul>
	<h1>{$t("pages.privacy.data_collecting.title")}</h1>
	<h2>{$t("pages.privacy.data_collecting.types.header")}</h2>
	<h3>{$t("pages.privacy.data_collecting.types.personal.header")}</h3>
	<p>
		{$t("pages.privacy.data_collecting.types.personal.description")}
	</p>
	<ul>
		<li>{$t("pages.privacy.data_collecting.types.personal.information")}</li>
	</ul>
	<h3>{$t("pages.privacy.data_collecting.types.usage_data.header")}</h3>
	<p>{$t("pages.privacy.data_collecting.types.usage_data.description_1")}</p>
	<p>
		{$t("pages.privacy.data_collecting.types.usage_data.description_2")}
	</p>
	<p>
		{$t("pages.privacy.data_collecting.types.usage_data.description_3")}
	</p>
	<p>
		{$t("pages.privacy.data_collecting.types.usage_data.description_4")}
	</p>
	<h3>{$t("pages.privacy.data_collecting.types.information_social_media.header")}</h3>
	<p>
		{$t("pages.privacy.data_collecting.types.information_social_media.description_1")}
	</p>
	<ul>
		<li>{$t("pages.privacy.data_collecting.types.information_social_media.twitch")}</li>
		<li>{$t("pages.privacy.data_collecting.types.information_social_media.youtube")}</li>
		<li>{$t("pages.privacy.data_collecting.types.information_social_media.discord")}</li>
	</ul>
	<p>
		{$t("pages.privacy.data_collecting.types.information_social_media.description_2")}
	</p>
	<p>
		{$t("pages.privacy.data_collecting.types.information_social_media.description_3")}
	</p>
	<h2>{$t("pages.privacy.data_collecting.use.header")}</h2>
	<p>{$t("pages.privacy.data_collecting.use.description_1")}</p>
	<ul>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.provide_maintain")}</strong>, {$t(
					"pages.privacy.data_collecting.use.provide_maintain_description",
				)}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.manage_account")}</strong>
				{$t("pages.privacy.data_collecting.use.manage_account_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.performance_of_contract")}</strong>
				{$t("pages.privacy.data_collecting.use.performance_of_contract_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.contact")}</strong>
				{$t("pages.privacy.data_collecting.use.contact_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.provide")}</strong>
				{$t("pages.privacy.data_collecting.use.provide_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.manage_requests")}</strong>
				{$t("pages.privacy.data_collecting.use.manage_requests_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.business_transfers")}</strong>
				{$t("pages.privacy.data_collecting.use.business_transfers_description")}
			</p>
		</li>
		<li>
			<p>
				<strong>{$t("pages.privacy.data_collecting.use.other")}</strong>
				{$t("pages.privacy.data_collecting.use.other_description")}
			</p>
		</li>
	</ul>
	<p>{$t("pages.privacy.data_collecting.use.share.description")}</p>
	<ul>
		<li>
			<strong>{$t("pages.privacy.data_collecting.use.share.service_providers")}</strong>
			{$t("pages.privacy.data_collecting.use.share.service_providers_description")}
		</li>
		<li>
			<strong>{$t("pages.privacy.data_collecting.use.share.business_transfers")}</strong>
			{$t("pages.privacy.data_collecting.use.share.business_transfers_description")}
		</li>
		<li>
			<strong>{$t("pages.privacy.data_collecting.use.share.affiliates")}</strong>
			{$t("pages.privacy.data_collecting.use.share.affiliates_description")}
		</li>
		<li>
			<strong>{$t("pages.privacy.data_collecting.use.share._business_partners")}</strong>
			{$t("pages.privacy.data_collecting.use.share.business_partners_description")}
		</li>
		<li>
			<strong>{$t("pages.privacy.data_collecting.use.share.other_users")}</strong>
			{$t("pages.privacy.data_collecting.use.share.other_users_description")}
		</li>
		<li>
			<strong>{$t("pages.privacy.data_collecting.use.share.consent")}</strong>
			{$t("pages.privacy.data_collecting.use.share.consent_description")}
		</li>
	</ul>
	<h2>{$t("pages.privacy.data_collecting.retention.header")}</h2>
	<p>
		{$t("pages.privacy.data_collecting.retention.description_1")}
	</p>
	<p>
		{$t("pages.privacy.data_collecting.retention.description_2")}
	</p>
	<h2>{$t("pages.privacy.data_collecting.transfer.header")}</h2>
	<p>
		{$t("pages.privacy.data_collecting.transfer.description_1")}
	</p>
	<p>
		{$t("pages.privacy.data_collecting.transfer.description_2")}
	</p>
	<p>
		{$t("pages.privacy.data_collecting.transfer.description_3")}
	</p>
	<h2>{$t("pages.privacy.data_collecting.disclosure.header")}</h2>
	<h3>{$t("pages.privacy.data_collecting.disclosure.business_transactions.header")}</h3>
	<p>
		{$t("pages.privacy.data_collecting.disclosure.business_transactions.description")}
	</p>
	<h3>{$t("pages.privacy.data_collecting.disclosure.law_enforcement.header")}</h3>
	<p>
		{$t("pages.privacy.data_collecting.disclosure.law_enforcement.description")}
	</p>
	<h3>{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.header")}</h3>
	<p>
		{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.description")}
	</p>
	<ul>
		<li>{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.bullet_1")}</li>
		<li>{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.bullet_2")}</li>
		<li>{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.bullet_3")}</li>
		<li>{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.bullet_4")}</li>
		<li>{$t("pages.privacy.data_collecting.disclosure.other_legal_requirements.bullet_5")}</li>
	</ul>
	<h2>{$t("pages.privacy.security.header")}</h2>
	<p>
		{$t("pages.privacy.security.description")}
	</p>
	<h1>
		{$t("pages.privacy.caloppa.title")}
	</h1>
	<p>{$t("pages.privacy.caloppa.description_1")}</p>
	<p>
		{$t("pages.privacy.caloppa.description_2")}
	</p>
	<h1>{$t("pages.privacy.children.title")}</h1>
	<p>
		{$t("pages.privacy.children.description_1")}
	</p>
	<p>
		{$t("pages.privacy.children.description_2")}
	</p>
	<h1>{$t("pages.privacy.links.title")}</h1>
	<p>
		{$t("pages.privacy.links.description_1")}
	</p>
	<p>
		{$t("pages.privacy.links.description_2")}
	</p>
	<h1>{$t("pages.privacy.changes.title")}</h1>
	<p>
		{$t("pages.privacy.changes.description_1")}
	</p>
	<p>
		{$t("pages.privacy.changes.description_2")}
	</p>
	<p>
		{$t("pages.privacy.changes.description_3")}
	</p>
	<h1>{$t("pages.privacy.contact.title")}</h1>
	<p>{$t("pages.privacy.contact.description")}</p>
	<ul>
		<li>{$t("pages.privacy.contact.email")}<a href="mailto:kathy@7tv.app"> kathy@7tv.app</a></li>
	</ul>
</div>

<style lang="scss">
	.page {
		max-width: 60rem;
		margin: 2rem auto;
		padding: 0 1rem;
	}

	h1 {
		margin: 1.4rem 0;
	}

	h2 {
		margin: 1.2rem 0;
	}

	h3 {
		margin: 1.1rem 0;
	}

	p {
		margin: 1rem 0;
	}

	ul {
		list-style: disc;
		margin: 1rem 0;
		padding-left: 1.5rem;
	}
</style>
