<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";

	const flags = {
		ad: new URL("$assets/flags/ad.png", import.meta.url).href,
		ae: new URL("$assets/flags/ae.png", import.meta.url).href,
		af: new URL("$assets/flags/af.png", import.meta.url).href,
		ag: new URL("$assets/flags/ag.png", import.meta.url).href,
		ai: new URL("$assets/flags/ai.png", import.meta.url).href,
		al: new URL("$assets/flags/al.png", import.meta.url).href,
		am: new URL("$assets/flags/am.png", import.meta.url).href,
		ao: new URL("$assets/flags/ao.png", import.meta.url).href,
		aq: new URL("$assets/flags/aq.png", import.meta.url).href,
		ar: new URL("$assets/flags/ar.png", import.meta.url).href,
		as: new URL("$assets/flags/as.png", import.meta.url).href,
		at: new URL("$assets/flags/at.png", import.meta.url).href,
		au: new URL("$assets/flags/au.png", import.meta.url).href,
		aw: new URL("$assets/flags/aw.png", import.meta.url).href,
		ax: new URL("$assets/flags/ax.png", import.meta.url).href,
		az: new URL("$assets/flags/az.png", import.meta.url).href,
		ba: new URL("$assets/flags/ba.png", import.meta.url).href,
		bb: new URL("$assets/flags/bb.png", import.meta.url).href,
		bd: new URL("$assets/flags/bd.png", import.meta.url).href,
		be: new URL("$assets/flags/be.png", import.meta.url).href,
		bf: new URL("$assets/flags/bf.png", import.meta.url).href,
		bg: new URL("$assets/flags/bg.png", import.meta.url).href,
		bh: new URL("$assets/flags/bh.png", import.meta.url).href,
		bi: new URL("$assets/flags/bi.png", import.meta.url).href,
		bj: new URL("$assets/flags/bj.png", import.meta.url).href,
		bl: new URL("$assets/flags/bl.png", import.meta.url).href,
		bm: new URL("$assets/flags/bm.png", import.meta.url).href,
		bn: new URL("$assets/flags/bn.png", import.meta.url).href,
		bo: new URL("$assets/flags/bo.png", import.meta.url).href,
		bq: new URL("$assets/flags/bq.png", import.meta.url).href,
		br: new URL("$assets/flags/br.png", import.meta.url).href,
		bs: new URL("$assets/flags/bs.png", import.meta.url).href,
		bt: new URL("$assets/flags/bt.png", import.meta.url).href,
		bv: new URL("$assets/flags/bv.png", import.meta.url).href,
		bw: new URL("$assets/flags/bw.png", import.meta.url).href,
		by: new URL("$assets/flags/by.png", import.meta.url).href,
		bz: new URL("$assets/flags/bz.png", import.meta.url).href,
		ca: new URL("$assets/flags/ca.png", import.meta.url).href,
		cc: new URL("$assets/flags/cc.png", import.meta.url).href,
		cd: new URL("$assets/flags/cd.png", import.meta.url).href,
		cf: new URL("$assets/flags/cf.png", import.meta.url).href,
		cg: new URL("$assets/flags/cg.png", import.meta.url).href,
		ch: new URL("$assets/flags/ch.png", import.meta.url).href,
		ci: new URL("$assets/flags/ci.png", import.meta.url).href,
		ck: new URL("$assets/flags/ck.png", import.meta.url).href,
		cl: new URL("$assets/flags/cl.png", import.meta.url).href,
		cm: new URL("$assets/flags/cm.png", import.meta.url).href,
		cn: new URL("$assets/flags/cn.png", import.meta.url).href,
		co: new URL("$assets/flags/co.png", import.meta.url).href,
		cr: new URL("$assets/flags/cr.png", import.meta.url).href,
		cu: new URL("$assets/flags/cu.png", import.meta.url).href,
		cv: new URL("$assets/flags/cv.png", import.meta.url).href,
		cw: new URL("$assets/flags/cw.png", import.meta.url).href,
		cx: new URL("$assets/flags/cx.png", import.meta.url).href,
		cy: new URL("$assets/flags/cy.png", import.meta.url).href,
		cz: new URL("$assets/flags/cz.png", import.meta.url).href,
		de: new URL("$assets/flags/de.png", import.meta.url).href,
		dj: new URL("$assets/flags/dj.png", import.meta.url).href,
		dk: new URL("$assets/flags/dk.png", import.meta.url).href,
		dm: new URL("$assets/flags/dm.png", import.meta.url).href,
		do: new URL("$assets/flags/do.png", import.meta.url).href,
		dz: new URL("$assets/flags/dz.png", import.meta.url).href,
		ec: new URL("$assets/flags/ec.png", import.meta.url).href,
		ee: new URL("$assets/flags/ee.png", import.meta.url).href,
		eg: new URL("$assets/flags/eg.png", import.meta.url).href,
		eh: new URL("$assets/flags/eh.png", import.meta.url).href,
		er: new URL("$assets/flags/er.png", import.meta.url).href,
		es: new URL("$assets/flags/es.png", import.meta.url).href,
		et: new URL("$assets/flags/et.png", import.meta.url).href,
		eu: new URL("$assets/flags/eu.png", import.meta.url).href,
		fi: new URL("$assets/flags/fi.png", import.meta.url).href,
		fj: new URL("$assets/flags/fj.png", import.meta.url).href,
		fk: new URL("$assets/flags/fk.png", import.meta.url).href,
		fm: new URL("$assets/flags/fm.png", import.meta.url).href,
		fo: new URL("$assets/flags/fo.png", import.meta.url).href,
		fr: new URL("$assets/flags/fr.png", import.meta.url).href,
		ga: new URL("$assets/flags/ga.png", import.meta.url).href,
		gb: new URL("$assets/flags/gb.png", import.meta.url).href,
		gd: new URL("$assets/flags/gd.png", import.meta.url).href,
		ge: new URL("$assets/flags/ge.png", import.meta.url).href,
		gf: new URL("$assets/flags/gf.png", import.meta.url).href,
		gg: new URL("$assets/flags/gg.png", import.meta.url).href,
		gh: new URL("$assets/flags/gh.png", import.meta.url).href,
		gi: new URL("$assets/flags/gi.png", import.meta.url).href,
		gl: new URL("$assets/flags/gl.png", import.meta.url).href,
		gm: new URL("$assets/flags/gm.png", import.meta.url).href,
		gn: new URL("$assets/flags/gn.png", import.meta.url).href,
		gp: new URL("$assets/flags/gp.png", import.meta.url).href,
		gq: new URL("$assets/flags/gq.png", import.meta.url).href,
		gr: new URL("$assets/flags/gr.png", import.meta.url).href,
		gs: new URL("$assets/flags/gs.png", import.meta.url).href,
		gt: new URL("$assets/flags/gt.png", import.meta.url).href,
		gu: new URL("$assets/flags/gu.png", import.meta.url).href,
		gw: new URL("$assets/flags/gw.png", import.meta.url).href,
		gy: new URL("$assets/flags/gy.png", import.meta.url).href,
		hk: new URL("$assets/flags/hk.png", import.meta.url).href,
		hm: new URL("$assets/flags/hm.png", import.meta.url).href,
		hn: new URL("$assets/flags/hn.png", import.meta.url).href,
		hr: new URL("$assets/flags/hr.png", import.meta.url).href,
		ht: new URL("$assets/flags/ht.png", import.meta.url).href,
		hu: new URL("$assets/flags/hu.png", import.meta.url).href,
		id: new URL("$assets/flags/id.png", import.meta.url).href,
		ie: new URL("$assets/flags/ie.png", import.meta.url).href,
		il: new URL("$assets/flags/il.png", import.meta.url).href,
		im: new URL("$assets/flags/im.png", import.meta.url).href,
		in: new URL("$assets/flags/in.png", import.meta.url).href,
		io: new URL("$assets/flags/io.png", import.meta.url).href,
		iq: new URL("$assets/flags/iq.png", import.meta.url).href,
		ir: new URL("$assets/flags/ir.png", import.meta.url).href,
		is: new URL("$assets/flags/is.png", import.meta.url).href,
		it: new URL("$assets/flags/it.png", import.meta.url).href,
		je: new URL("$assets/flags/je.png", import.meta.url).href,
		jm: new URL("$assets/flags/jm.png", import.meta.url).href,
		jo: new URL("$assets/flags/jo.png", import.meta.url).href,
		jp: new URL("$assets/flags/jp.png", import.meta.url).href,
		ke: new URL("$assets/flags/ke.png", import.meta.url).href,
		kg: new URL("$assets/flags/kg.png", import.meta.url).href,
		kh: new URL("$assets/flags/kh.png", import.meta.url).href,
		ki: new URL("$assets/flags/ki.png", import.meta.url).href,
		km: new URL("$assets/flags/km.png", import.meta.url).href,
		kn: new URL("$assets/flags/kn.png", import.meta.url).href,
		kp: new URL("$assets/flags/kp.png", import.meta.url).href,
		kr: new URL("$assets/flags/kr.png", import.meta.url).href,
		kw: new URL("$assets/flags/kw.png", import.meta.url).href,
		ky: new URL("$assets/flags/ky.png", import.meta.url).href,
		kz: new URL("$assets/flags/kz.png", import.meta.url).href,
		la: new URL("$assets/flags/la.png", import.meta.url).href,
		lb: new URL("$assets/flags/lb.png", import.meta.url).href,
		lc: new URL("$assets/flags/lc.png", import.meta.url).href,
		li: new URL("$assets/flags/li.png", import.meta.url).href,
		lk: new URL("$assets/flags/lk.png", import.meta.url).href,
		lr: new URL("$assets/flags/lr.png", import.meta.url).href,
		ls: new URL("$assets/flags/ls.png", import.meta.url).href,
		lt: new URL("$assets/flags/lt.png", import.meta.url).href,
		lu: new URL("$assets/flags/lu.png", import.meta.url).href,
		lv: new URL("$assets/flags/lv.png", import.meta.url).href,
		ly: new URL("$assets/flags/ly.png", import.meta.url).href,
		ma: new URL("$assets/flags/ma.png", import.meta.url).href,
		mc: new URL("$assets/flags/mc.png", import.meta.url).href,
		md: new URL("$assets/flags/md.png", import.meta.url).href,
		me: new URL("$assets/flags/me.png", import.meta.url).href,
		mf: new URL("$assets/flags/mf.png", import.meta.url).href,
		mg: new URL("$assets/flags/mg.png", import.meta.url).href,
		mh: new URL("$assets/flags/mh.png", import.meta.url).href,
		mk: new URL("$assets/flags/mk.png", import.meta.url).href,
		ml: new URL("$assets/flags/ml.png", import.meta.url).href,
		mm: new URL("$assets/flags/mm.png", import.meta.url).href,
		mn: new URL("$assets/flags/mn.png", import.meta.url).href,
		mo: new URL("$assets/flags/mo.png", import.meta.url).href,
		mp: new URL("$assets/flags/mp.png", import.meta.url).href,
		mq: new URL("$assets/flags/mq.png", import.meta.url).href,
		mr: new URL("$assets/flags/mr.png", import.meta.url).href,
		ms: new URL("$assets/flags/ms.png", import.meta.url).href,
		mt: new URL("$assets/flags/mt.png", import.meta.url).href,
		mu: new URL("$assets/flags/mu.png", import.meta.url).href,
		mv: new URL("$assets/flags/mv.png", import.meta.url).href,
		mw: new URL("$assets/flags/mw.png", import.meta.url).href,
		mx: new URL("$assets/flags/mx.png", import.meta.url).href,
		my: new URL("$assets/flags/my.png", import.meta.url).href,
		mz: new URL("$assets/flags/mz.png", import.meta.url).href,
		na: new URL("$assets/flags/na.png", import.meta.url).href,
		nc: new URL("$assets/flags/nc.png", import.meta.url).href,
		ne: new URL("$assets/flags/ne.png", import.meta.url).href,
		nf: new URL("$assets/flags/nf.png", import.meta.url).href,
		ng: new URL("$assets/flags/ng.png", import.meta.url).href,
		ni: new URL("$assets/flags/ni.png", import.meta.url).href,
		nl: new URL("$assets/flags/nl.png", import.meta.url).href,
		no: new URL("$assets/flags/no.png", import.meta.url).href,
		np: new URL("$assets/flags/np.png", import.meta.url).href,
		nr: new URL("$assets/flags/nr.png", import.meta.url).href,
		nu: new URL("$assets/flags/nu.png", import.meta.url).href,
		nz: new URL("$assets/flags/nz.png", import.meta.url).href,
		om: new URL("$assets/flags/om.png", import.meta.url).href,
		pa: new URL("$assets/flags/pa.png", import.meta.url).href,
		pe: new URL("$assets/flags/pe.png", import.meta.url).href,
		pf: new URL("$assets/flags/pf.png", import.meta.url).href,
		pg: new URL("$assets/flags/pg.png", import.meta.url).href,
		ph: new URL("$assets/flags/ph.png", import.meta.url).href,
		pk: new URL("$assets/flags/pk.png", import.meta.url).href,
		pl: new URL("$assets/flags/pl.png", import.meta.url).href,
		pm: new URL("$assets/flags/pm.png", import.meta.url).href,
		pn: new URL("$assets/flags/pn.png", import.meta.url).href,
		pr: new URL("$assets/flags/pr.png", import.meta.url).href,
		ps: new URL("$assets/flags/ps.png", import.meta.url).href,
		pt: new URL("$assets/flags/pt.png", import.meta.url).href,
		pw: new URL("$assets/flags/pw.png", import.meta.url).href,
		py: new URL("$assets/flags/py.png", import.meta.url).href,
		qa: new URL("$assets/flags/qa.png", import.meta.url).href,
		re: new URL("$assets/flags/re.png", import.meta.url).href,
		ro: new URL("$assets/flags/ro.png", import.meta.url).href,
		rs: new URL("$assets/flags/rs.png", import.meta.url).href,
		ru: new URL("$assets/flags/ru.png", import.meta.url).href,
		rw: new URL("$assets/flags/rw.png", import.meta.url).href,
		sa: new URL("$assets/flags/sa.png", import.meta.url).href,
		sb: new URL("$assets/flags/sb.png", import.meta.url).href,
		sc: new URL("$assets/flags/sc.png", import.meta.url).href,
		sd: new URL("$assets/flags/sd.png", import.meta.url).href,
		se: new URL("$assets/flags/se.png", import.meta.url).href,
		sg: new URL("$assets/flags/sg.png", import.meta.url).href,
		sh: new URL("$assets/flags/sh.png", import.meta.url).href,
		si: new URL("$assets/flags/si.png", import.meta.url).href,
		sj: new URL("$assets/flags/sj.png", import.meta.url).href,
		sk: new URL("$assets/flags/sk.png", import.meta.url).href,
		sl: new URL("$assets/flags/sl.png", import.meta.url).href,
		sm: new URL("$assets/flags/sm.png", import.meta.url).href,
		sn: new URL("$assets/flags/sn.png", import.meta.url).href,
		so: new URL("$assets/flags/so.png", import.meta.url).href,
		sr: new URL("$assets/flags/sr.png", import.meta.url).href,
		ss: new URL("$assets/flags/ss.png", import.meta.url).href,
		st: new URL("$assets/flags/st.png", import.meta.url).href,
		sv: new URL("$assets/flags/sv.png", import.meta.url).href,
		sx: new URL("$assets/flags/sx.png", import.meta.url).href,
		sy: new URL("$assets/flags/sy.png", import.meta.url).href,
		sz: new URL("$assets/flags/sz.png", import.meta.url).href,
		tc: new URL("$assets/flags/tc.png", import.meta.url).href,
		td: new URL("$assets/flags/td.png", import.meta.url).href,
		tf: new URL("$assets/flags/tf.png", import.meta.url).href,
		tg: new URL("$assets/flags/tg.png", import.meta.url).href,
		th: new URL("$assets/flags/th.png", import.meta.url).href,
		tj: new URL("$assets/flags/tj.png", import.meta.url).href,
		tk: new URL("$assets/flags/tk.png", import.meta.url).href,
		tl: new URL("$assets/flags/tl.png", import.meta.url).href,
		tm: new URL("$assets/flags/tm.png", import.meta.url).href,
		tn: new URL("$assets/flags/tn.png", import.meta.url).href,
		to: new URL("$assets/flags/to.png", import.meta.url).href,
		tr: new URL("$assets/flags/tr.png", import.meta.url).href,
		tt: new URL("$assets/flags/tt.png", import.meta.url).href,
		tv: new URL("$assets/flags/tv.png", import.meta.url).href,
		tw: new URL("$assets/flags/tw.png", import.meta.url).href,
		tz: new URL("$assets/flags/tz.png", import.meta.url).href,
		ua: new URL("$assets/flags/ua.png", import.meta.url).href,
		ug: new URL("$assets/flags/ug.png", import.meta.url).href,
		um: new URL("$assets/flags/um.png", import.meta.url).href,
		us: new URL("$assets/flags/us.png", import.meta.url).href,
		uy: new URL("$assets/flags/uy.png", import.meta.url).href,
		uz: new URL("$assets/flags/uz.png", import.meta.url).href,
		va: new URL("$assets/flags/va.png", import.meta.url).href,
		vc: new URL("$assets/flags/vc.png", import.meta.url).href,
		ve: new URL("$assets/flags/ve.png", import.meta.url).href,
		vg: new URL("$assets/flags/vg.png", import.meta.url).href,
		vi: new URL("$assets/flags/vi.png", import.meta.url).href,
		vn: new URL("$assets/flags/vn.png", import.meta.url).href,
		vu: new URL("$assets/flags/vu.png", import.meta.url).href,
		wf: new URL("$assets/flags/wf.png", import.meta.url).href,
		ws: new URL("$assets/flags/ws.png", import.meta.url).href,
		xk: new URL("$assets/flags/xk.png", import.meta.url).href,
		ye: new URL("$assets/flags/ye.png", import.meta.url).href,
		yt: new URL("$assets/flags/yt.png", import.meta.url).href,
		za: new URL("$assets/flags/za.png", import.meta.url).href,
		zm: new URL("$assets/flags/zm.png", import.meta.url).href,
		zw: new URL("$assets/flags/zw.png", import.meta.url).href,
	};

	type Props = {
		code: string;
		name: string;
		width?: number;
		height?: number;
	} & HTMLAttributes<HTMLImageElement>;

	let { code, name, width, height, ...restProps }: Props = $props();
</script>

<img
	src={flags[code.toLowerCase() as keyof typeof flags]}
	alt={name}
	title={name}
	class="flag"
	width="{width}px"
	height="{height}px"
	{...restProps}
/>

<style lang="scss">
	.flag {
		border-radius: 0.25rem;
	}
</style>
