<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";

	const flags = {
		"ad": new URL("$assets/flags/ad.svg", import.meta.url).href,
		"ae": new URL("$assets/flags/ae.svg", import.meta.url).href,
		"af": new URL("$assets/flags/af.svg", import.meta.url).href,
		"ag": new URL("$assets/flags/ag.svg", import.meta.url).href,
		"ai": new URL("$assets/flags/ai.svg", import.meta.url).href,
		"al": new URL("$assets/flags/al.svg", import.meta.url).href,
		"am": new URL("$assets/flags/am.svg", import.meta.url).href,
		"ao": new URL("$assets/flags/ao.svg", import.meta.url).href,
		"aq": new URL("$assets/flags/aq.svg", import.meta.url).href,
		"ar": new URL("$assets/flags/ar.svg", import.meta.url).href,
		"as": new URL("$assets/flags/as.svg", import.meta.url).href,
		"at": new URL("$assets/flags/at.svg", import.meta.url).href,
		"au": new URL("$assets/flags/au.svg", import.meta.url).href,
		"aw": new URL("$assets/flags/aw.svg", import.meta.url).href,
		"ax": new URL("$assets/flags/ax.svg", import.meta.url).href,
		"az": new URL("$assets/flags/az.svg", import.meta.url).href,
		"ba": new URL("$assets/flags/ba.svg", import.meta.url).href,
		"bb": new URL("$assets/flags/bb.svg", import.meta.url).href,
		"bd": new URL("$assets/flags/bd.svg", import.meta.url).href,
		"be": new URL("$assets/flags/be.svg", import.meta.url).href,
		"bf": new URL("$assets/flags/bf.svg", import.meta.url).href,
		"bg": new URL("$assets/flags/bg.svg", import.meta.url).href,
		"bh": new URL("$assets/flags/bh.svg", import.meta.url).href,
		"bi": new URL("$assets/flags/bi.svg", import.meta.url).href,
		"bj": new URL("$assets/flags/bj.svg", import.meta.url).href,
		"bl": new URL("$assets/flags/bl.svg", import.meta.url).href,
		"bm": new URL("$assets/flags/bm.svg", import.meta.url).href,
		"bn": new URL("$assets/flags/bn.svg", import.meta.url).href,
		"bo": new URL("$assets/flags/bo.svg", import.meta.url).href,
		"bq": new URL("$assets/flags/bq.svg", import.meta.url).href,
		"br": new URL("$assets/flags/br.svg", import.meta.url).href,
		"bs": new URL("$assets/flags/bs.svg", import.meta.url).href,
		"bt": new URL("$assets/flags/bt.svg", import.meta.url).href,
		"bv": new URL("$assets/flags/bv.svg", import.meta.url).href,
		"bw": new URL("$assets/flags/bw.svg", import.meta.url).href,
		"by": new URL("$assets/flags/by.svg", import.meta.url).href,
		"bz": new URL("$assets/flags/bz.svg", import.meta.url).href,
		"ca": new URL("$assets/flags/ca.svg", import.meta.url).href,
		"cc": new URL("$assets/flags/cc.svg", import.meta.url).href,
		"cd": new URL("$assets/flags/cd.svg", import.meta.url).href,
		"cf": new URL("$assets/flags/cf.svg", import.meta.url).href,
		"cg": new URL("$assets/flags/cg.svg", import.meta.url).href,
		"ch": new URL("$assets/flags/ch.svg", import.meta.url).href,
		"ci": new URL("$assets/flags/ci.svg", import.meta.url).href,
		"ck": new URL("$assets/flags/ck.svg", import.meta.url).href,
		"cl": new URL("$assets/flags/cl.svg", import.meta.url).href,
		"cm": new URL("$assets/flags/cm.svg", import.meta.url).href,
		"cn": new URL("$assets/flags/cn.svg", import.meta.url).href,
		"co": new URL("$assets/flags/co.svg", import.meta.url).href,
		"cr": new URL("$assets/flags/cr.svg", import.meta.url).href,
		"cu": new URL("$assets/flags/cu.svg", import.meta.url).href,
		"cv": new URL("$assets/flags/cv.svg", import.meta.url).href,
		"cw": new URL("$assets/flags/cw.svg", import.meta.url).href,
		"cx": new URL("$assets/flags/cx.svg", import.meta.url).href,
		"cy": new URL("$assets/flags/cy.svg", import.meta.url).href,
		"cz": new URL("$assets/flags/cz.svg", import.meta.url).href,
		"de": new URL("$assets/flags/de.svg", import.meta.url).href,
		"dj": new URL("$assets/flags/dj.svg", import.meta.url).href,
		"dk": new URL("$assets/flags/dk.svg", import.meta.url).href,
		"dm": new URL("$assets/flags/dm.svg", import.meta.url).href,
		"do": new URL("$assets/flags/do.svg", import.meta.url).href,
		"dz": new URL("$assets/flags/dz.svg", import.meta.url).href,
		"ec": new URL("$assets/flags/ec.svg", import.meta.url).href,
		"ee": new URL("$assets/flags/ee.svg", import.meta.url).href,
		"eg": new URL("$assets/flags/eg.svg", import.meta.url).href,
		"eh": new URL("$assets/flags/eh.svg", import.meta.url).href,
		"er": new URL("$assets/flags/er.svg", import.meta.url).href,
		"es": new URL("$assets/flags/es.svg", import.meta.url).href,
		"et": new URL("$assets/flags/et.svg", import.meta.url).href,
		"eu": new URL("$assets/flags/eu.svg", import.meta.url).href,
		"fi": new URL("$assets/flags/fi.svg", import.meta.url).href,
		"fj": new URL("$assets/flags/fj.svg", import.meta.url).href,
		"fk": new URL("$assets/flags/fk.svg", import.meta.url).href,
		"fm": new URL("$assets/flags/fm.svg", import.meta.url).href,
		"fo": new URL("$assets/flags/fo.svg", import.meta.url).href,
		"fr": new URL("$assets/flags/fr.svg", import.meta.url).href,
		"ga": new URL("$assets/flags/ga.svg", import.meta.url).href,
		"gb-eng": new URL("$assets/flags/eng, import.meta.url.svg").href,
		"gb-nir": new URL("$assets/flags/nir, import.meta.url.svg").href,
		"gb-sct": new URL("$assets/flags/sct, import.meta.url.svg").href,
		"gb-wls": new URL("$assets/flags/wls, import.meta.url.svg").href,
		"gb": new URL("$assets/flags/gb.svg", import.meta.url).href,
		"gd": new URL("$assets/flags/gd.svg", import.meta.url).href,
		"ge": new URL("$assets/flags/ge.svg", import.meta.url).href,
		"gf": new URL("$assets/flags/gf.svg", import.meta.url).href,
		"gg": new URL("$assets/flags/gg.svg", import.meta.url).href,
		"gh": new URL("$assets/flags/gh.svg", import.meta.url).href,
		"gi": new URL("$assets/flags/gi.svg", import.meta.url).href,
		"gl": new URL("$assets/flags/gl.svg", import.meta.url).href,
		"gm": new URL("$assets/flags/gm.svg", import.meta.url).href,
		"gn": new URL("$assets/flags/gn.svg", import.meta.url).href,
		"gp": new URL("$assets/flags/gp.svg", import.meta.url).href,
		"gq": new URL("$assets/flags/gq.svg", import.meta.url).href,
		"gr": new URL("$assets/flags/gr.svg", import.meta.url).href,
		"gs": new URL("$assets/flags/gs.svg", import.meta.url).href,
		"gt": new URL("$assets/flags/gt.svg", import.meta.url).href,
		"gu": new URL("$assets/flags/gu.svg", import.meta.url).href,
		"gw": new URL("$assets/flags/gw.svg", import.meta.url).href,
		"gy": new URL("$assets/flags/gy.svg", import.meta.url).href,
		"hk": new URL("$assets/flags/hk.svg", import.meta.url).href,
		"hm": new URL("$assets/flags/hm.svg", import.meta.url).href,
		"hn": new URL("$assets/flags/hn.svg", import.meta.url).href,
		"hr": new URL("$assets/flags/hr.svg", import.meta.url).href,
		"ht": new URL("$assets/flags/ht.svg", import.meta.url).href,
		"hu": new URL("$assets/flags/hu.svg", import.meta.url).href,
		"id": new URL("$assets/flags/id.svg", import.meta.url).href,
		"ie": new URL("$assets/flags/ie.svg", import.meta.url).href,
		"il": new URL("$assets/flags/il.svg", import.meta.url).href,
		"im": new URL("$assets/flags/im.svg", import.meta.url).href,
		"in": new URL("$assets/flags/in.svg", import.meta.url).href,
		"io": new URL("$assets/flags/io.svg", import.meta.url).href,
		"iq": new URL("$assets/flags/iq.svg", import.meta.url).href,
		"ir": new URL("$assets/flags/ir.svg", import.meta.url).href,
		"is": new URL("$assets/flags/is.svg", import.meta.url).href,
		"it": new URL("$assets/flags/it.svg", import.meta.url).href,
		"je": new URL("$assets/flags/je.svg", import.meta.url).href,
		"jm": new URL("$assets/flags/jm.svg", import.meta.url).href,
		"jo": new URL("$assets/flags/jo.svg", import.meta.url).href,
		"jp": new URL("$assets/flags/jp.svg", import.meta.url).href,
		"ke": new URL("$assets/flags/ke.svg", import.meta.url).href,
		"kg": new URL("$assets/flags/kg.svg", import.meta.url).href,
		"kh": new URL("$assets/flags/kh.svg", import.meta.url).href,
		"ki": new URL("$assets/flags/ki.svg", import.meta.url).href,
		"km": new URL("$assets/flags/km.svg", import.meta.url).href,
		"kn": new URL("$assets/flags/kn.svg", import.meta.url).href,
		"kp": new URL("$assets/flags/kp.svg", import.meta.url).href,
		"kr": new URL("$assets/flags/kr.svg", import.meta.url).href,
		"kw": new URL("$assets/flags/kw.svg", import.meta.url).href,
		"ky": new URL("$assets/flags/ky.svg", import.meta.url).href,
		"kz": new URL("$assets/flags/kz.svg", import.meta.url).href,
		"la": new URL("$assets/flags/la.svg", import.meta.url).href,
		"lb": new URL("$assets/flags/lb.svg", import.meta.url).href,
		"lc": new URL("$assets/flags/lc.svg", import.meta.url).href,
		"li": new URL("$assets/flags/li.svg", import.meta.url).href,
		"lk": new URL("$assets/flags/lk.svg", import.meta.url).href,
		"lr": new URL("$assets/flags/lr.svg", import.meta.url).href,
		"ls": new URL("$assets/flags/ls.svg", import.meta.url).href,
		"lt": new URL("$assets/flags/lt.svg", import.meta.url).href,
		"lu": new URL("$assets/flags/lu.svg", import.meta.url).href,
		"lv": new URL("$assets/flags/lv.svg", import.meta.url).href,
		"ly": new URL("$assets/flags/ly.svg", import.meta.url).href,
		"ma": new URL("$assets/flags/ma.svg", import.meta.url).href,
		"mc": new URL("$assets/flags/mc.svg", import.meta.url).href,
		"md": new URL("$assets/flags/md.svg", import.meta.url).href,
		"me": new URL("$assets/flags/me.svg", import.meta.url).href,
		"mf": new URL("$assets/flags/mf.svg", import.meta.url).href,
		"mg": new URL("$assets/flags/mg.svg", import.meta.url).href,
		"mh": new URL("$assets/flags/mh.svg", import.meta.url).href,
		"mk": new URL("$assets/flags/mk.svg", import.meta.url).href,
		"ml": new URL("$assets/flags/ml.svg", import.meta.url).href,
		"mm": new URL("$assets/flags/mm.svg", import.meta.url).href,
		"mn": new URL("$assets/flags/mn.svg", import.meta.url).href,
		"mo": new URL("$assets/flags/mo.svg", import.meta.url).href,
		"mp": new URL("$assets/flags/mp.svg", import.meta.url).href,
		"mq": new URL("$assets/flags/mq.svg", import.meta.url).href,
		"mr": new URL("$assets/flags/mr.svg", import.meta.url).href,
		"ms": new URL("$assets/flags/ms.svg", import.meta.url).href,
		"mt": new URL("$assets/flags/mt.svg", import.meta.url).href,
		"mu": new URL("$assets/flags/mu.svg", import.meta.url).href,
		"mv": new URL("$assets/flags/mv.svg", import.meta.url).href,
		"mw": new URL("$assets/flags/mw.svg", import.meta.url).href,
		"mx": new URL("$assets/flags/mx.svg", import.meta.url).href,
		"my": new URL("$assets/flags/my.svg", import.meta.url).href,
		"mz": new URL("$assets/flags/mz.svg", import.meta.url).href,
		"na": new URL("$assets/flags/na.svg", import.meta.url).href,
		"nc": new URL("$assets/flags/nc.svg", import.meta.url).href,
		"ne": new URL("$assets/flags/ne.svg", import.meta.url).href,
		"nf": new URL("$assets/flags/nf.svg", import.meta.url).href,
		"ng": new URL("$assets/flags/ng.svg", import.meta.url).href,
		"ni": new URL("$assets/flags/ni.svg", import.meta.url).href,
		"nl": new URL("$assets/flags/nl.svg", import.meta.url).href,
		"no": new URL("$assets/flags/no.svg", import.meta.url).href,
		"np": new URL("$assets/flags/np.svg", import.meta.url).href,
		"nr": new URL("$assets/flags/nr.svg", import.meta.url).href,
		"nu": new URL("$assets/flags/nu.svg", import.meta.url).href,
		"nz": new URL("$assets/flags/nz.svg", import.meta.url).href,
		"om": new URL("$assets/flags/om.svg", import.meta.url).href,
		"pa": new URL("$assets/flags/pa.svg", import.meta.url).href,
		"pe": new URL("$assets/flags/pe.svg", import.meta.url).href,
		"pf": new URL("$assets/flags/pf.svg", import.meta.url).href,
		"pg": new URL("$assets/flags/pg.svg", import.meta.url).href,
		"ph": new URL("$assets/flags/ph.svg", import.meta.url).href,
		"pk": new URL("$assets/flags/pk.svg", import.meta.url).href,
		"pl": new URL("$assets/flags/pl.svg", import.meta.url).href,
		"pm": new URL("$assets/flags/pm.svg", import.meta.url).href,
		"pn": new URL("$assets/flags/pn.svg", import.meta.url).href,
		"pr": new URL("$assets/flags/pr.svg", import.meta.url).href,
		"ps": new URL("$assets/flags/ps.svg", import.meta.url).href,
		"pt": new URL("$assets/flags/pt.svg", import.meta.url).href,
		"pw": new URL("$assets/flags/pw.svg", import.meta.url).href,
		"py": new URL("$assets/flags/py.svg", import.meta.url).href,
		"qa": new URL("$assets/flags/qa.svg", import.meta.url).href,
		"re": new URL("$assets/flags/re.svg", import.meta.url).href,
		"ro": new URL("$assets/flags/ro.svg", import.meta.url).href,
		"rs": new URL("$assets/flags/rs.svg", import.meta.url).href,
		"ru": new URL("$assets/flags/ru.svg", import.meta.url).href,
		"rw": new URL("$assets/flags/rw.svg", import.meta.url).href,
		"sa": new URL("$assets/flags/sa.svg", import.meta.url).href,
		"sb": new URL("$assets/flags/sb.svg", import.meta.url).href,
		"sc": new URL("$assets/flags/sc.svg", import.meta.url).href,
		"sd": new URL("$assets/flags/sd.svg", import.meta.url).href,
		"se": new URL("$assets/flags/se.svg", import.meta.url).href,
		"sg": new URL("$assets/flags/sg.svg", import.meta.url).href,
		"sh": new URL("$assets/flags/sh.svg", import.meta.url).href,
		"si": new URL("$assets/flags/si.svg", import.meta.url).href,
		"sj": new URL("$assets/flags/sj.svg", import.meta.url).href,
		"sk": new URL("$assets/flags/sk.svg", import.meta.url).href,
		"sl": new URL("$assets/flags/sl.svg", import.meta.url).href,
		"sm": new URL("$assets/flags/sm.svg", import.meta.url).href,
		"sn": new URL("$assets/flags/sn.svg", import.meta.url).href,
		"so": new URL("$assets/flags/so.svg", import.meta.url).href,
		"sr": new URL("$assets/flags/sr.svg", import.meta.url).href,
		"ss": new URL("$assets/flags/ss.svg", import.meta.url).href,
		"st": new URL("$assets/flags/st.svg", import.meta.url).href,
		"sv": new URL("$assets/flags/sv.svg", import.meta.url).href,
		"sx": new URL("$assets/flags/sx.svg", import.meta.url).href,
		"sy": new URL("$assets/flags/sy.svg", import.meta.url).href,
		"sz": new URL("$assets/flags/sz.svg", import.meta.url).href,
		"tc": new URL("$assets/flags/tc.svg", import.meta.url).href,
		"td": new URL("$assets/flags/td.svg", import.meta.url).href,
		"tf": new URL("$assets/flags/tf.svg", import.meta.url).href,
		"tg": new URL("$assets/flags/tg.svg", import.meta.url).href,
		"th": new URL("$assets/flags/th.svg", import.meta.url).href,
		"tj": new URL("$assets/flags/tj.svg", import.meta.url).href,
		"tk": new URL("$assets/flags/tk.svg", import.meta.url).href,
		"tl": new URL("$assets/flags/tl.svg", import.meta.url).href,
		"tm": new URL("$assets/flags/tm.svg", import.meta.url).href,
		"tn": new URL("$assets/flags/tn.svg", import.meta.url).href,
		"to": new URL("$assets/flags/to.svg", import.meta.url).href,
		"tr": new URL("$assets/flags/tr.svg", import.meta.url).href,
		"tt": new URL("$assets/flags/tt.svg", import.meta.url).href,
		"tv": new URL("$assets/flags/tv.svg", import.meta.url).href,
		"tw": new URL("$assets/flags/tw.svg", import.meta.url).href,
		"tz": new URL("$assets/flags/tz.svg", import.meta.url).href,
		"ua": new URL("$assets/flags/ua.svg", import.meta.url).href,
		"ug": new URL("$assets/flags/ug.svg", import.meta.url).href,
		"um": new URL("$assets/flags/um.svg", import.meta.url).href,
		"us": new URL("$assets/flags/us.svg", import.meta.url).href,
		"uy": new URL("$assets/flags/uy.svg", import.meta.url).href,
		"uz": new URL("$assets/flags/uz.svg", import.meta.url).href,
		"va": new URL("$assets/flags/va.svg", import.meta.url).href,
		"vc": new URL("$assets/flags/vc.svg", import.meta.url).href,
		"ve": new URL("$assets/flags/ve.svg", import.meta.url).href,
		"vg": new URL("$assets/flags/vg.svg", import.meta.url).href,
		"vi": new URL("$assets/flags/vi.svg", import.meta.url).href,
		"vn": new URL("$assets/flags/vn.svg", import.meta.url).href,
		"vu": new URL("$assets/flags/vu.svg", import.meta.url).href,
		"wf": new URL("$assets/flags/wf.svg", import.meta.url).href,
		"ws": new URL("$assets/flags/ws.svg", import.meta.url).href,
		"xk": new URL("$assets/flags/xk.svg", import.meta.url).href,
		"ye": new URL("$assets/flags/ye.svg", import.meta.url).href,
		"yt": new URL("$assets/flags/yt.svg", import.meta.url).href,
		"za": new URL("$assets/flags/za.svg", import.meta.url).href,
		"zm": new URL("$assets/flags/zm.svg", import.meta.url).href,
		"zw": new URL("$assets/flags/zw.svg", import.meta.url).href,
	};

	type Props = {
		code: keyof typeof flags;
		name: string;
		width?: number;
		height?: number;
	} & HTMLAttributes<HTMLImageElement>;

	let { code, name, width, height, ...restProps }: Props = $props();
</script>

<img
	src={flags[code]}
	alt={name}
	title={name}
	class="flag"
	width="{width}px"
	height="{height}px"
	{...restProps}
/>

<style lang="scss">
	.flag {
		border-radius: 0.25rem;
	}
</style>
